export default function AboutPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '40px 20px' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '60px' }}>
          <h1 style={{ fontSize: '3em', color: 'white', marginBottom: '20px', textShadow: '2px 2px 4px rgba(0,0,0,0.2)' }}>
            About TradeFlow
          </h1>
          <p style={{ fontSize: '1.3em', color: 'rgba(255,255,255,0.9)', maxWidth: '800px', margin: '0 auto' }}>
            Your trusted partner in global trading education and market intelligence
          </p>
        </div>

        {/* Main Content */}
        <div style={{ background: 'white', borderRadius: '20px', padding: '50px', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
          {/* Mission Section */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              🎯 Our Mission
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              TradeFlow is dedicated to democratizing access to professional-grade trading signals and market analysis. We combine cutting-edge AI technology with expert market insights to provide traders worldwide with actionable intelligence.
            </p>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333' }}>
              Our mission is to empower traders of all levels—from beginners to professionals—with the tools, knowledge, and confidence they need to navigate global financial markets successfully.
            </p>
          </section>

          {/* What We Offer */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              🚀 What We Offer
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '30px', marginTop: '30px' }}>
              <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #667eea' }}>
                <h3 style={{ fontSize: '1.5em', color: '#667eea', marginBottom: '15px' }}>⚡ AI-Powered Signals</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Real-time trading signals generated by advanced AI algorithms analyzing global markets 24/7. Coverage includes stocks, forex, commodities, and cryptocurrencies.
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #764ba2' }}>
                <h3 style={{ fontSize: '1.5em', color: '#764ba2', marginBottom: '15px' }}>📊 Market Analysis</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  In-depth technical and fundamental analysis of major markets, helping you understand market trends and make informed decisions.
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #f093fb' }}>
                <h3 style={{ fontSize: '1.5em', color: '#f093fb', marginBottom: '15px' }}>🎓 Trading Education</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Comprehensive educational resources including tutorials, webinars, and strategy guides to accelerate your trading journey.
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #00c853' }}>
                <h3 style={{ fontSize: '1.5em', color: '#00c853', marginBottom: '15px' }}>🤝 Broker Partnerships</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Verified partnerships with regulated brokers like Exness, ensuring you have access to reliable trading platforms with competitive conditions.
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #ff1744' }}>
                <h3 style={{ fontSize: '1.5em', color: '#ff1744', marginBottom: '15px' }}>📰 Market News</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Real-time financial news aggregation and sentiment analysis to keep you informed about market-moving events.
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #2684ff' }}>
                <h3 style={{ fontSize: '1.5em', color: '#2684ff', marginBottom: '15px' }}>🌍 Global Coverage</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Multi-language support and coverage of global markets including US, European, Asian, and emerging markets.
                </p>
              </div>
            </div>
          </section>

          {/* Our Technology */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              🤖 Our Technology
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              TradeFlow leverages OpenAI's GPT-5 Nano model to analyze vast amounts of market data, news, and technical indicators in real-time. Our AI system:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Processes millions of data points daily from global financial markets</li>
              <li>Identifies high-probability trading opportunities across multiple asset classes</li>
              <li>Generates signals with detailed entry, target, and stop-loss levels</li>
              <li>Provides confidence scores based on technical and fundamental factors</li>
              <li>Continuously learns and adapts to changing market conditions</li>
            </ul>
          </section>

          {/* Why Choose Us */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              ⭐ Why Choose TradeFlow?
            </h2>
            <div style={{ background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', padding: '40px', borderRadius: '15px', color: 'white', marginTop: '30px' }}>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '30px' }}>
                <div>
                  <h3 style={{ fontSize: '2.5em', marginBottom: '10px' }}>10,247+</h3>
                  <p style={{ fontSize: '1.1em', opacity: 0.9 }}>Active Traders</p>
                </div>
                <div>
                  <h3 style={{ fontSize: '2.5em', marginBottom: '10px' }}>$2.4M+</h3>
                  <p style={{ fontSize: '1.1em', opacity: 0.9 }}>Total Profits Made</p>
                </div>
                <div>
                  <h3 style={{ fontSize: '2.5em', marginBottom: '10px' }}>78%</h3>
                  <p style={{ fontSize: '1.1em', opacity: 0.9 }}>Average Win Rate</p>
                </div>
                <div>
                  <h3 style={{ fontSize: '2.5em', marginBottom: '10px' }}>4.8★</h3>
                  <p style={{ fontSize: '1.1em', opacity: 0.9 }}>User Rating</p>
                </div>
              </div>
            </div>
          </section>

          {/* Our Commitment */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              🛡️ Our Commitment
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              At TradeFlow, we are committed to:
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginTop: '20px' }}>
              <div style={{ display: 'flex', alignItems: 'start', gap: '15px' }}>
                <span style={{ fontSize: '2em' }}>🔒</span>
                <div>
                  <h4 style={{ fontSize: '1.3em', color: '#667eea', marginBottom: '8px' }}>Security & Privacy</h4>
                  <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>Your data is encrypted and protected with industry-leading security standards.</p>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'start', gap: '15px' }}>
                <span style={{ fontSize: '2em' }}>📈</span>
                <div>
                  <h4 style={{ fontSize: '1.3em', color: '#667eea', marginBottom: '8px' }}>Transparency</h4>
                  <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>All signals include detailed analysis, rationale, and historical performance metrics.</p>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'start', gap: '15px' }}>
                <span style={{ fontSize: '2em' }}>🎯</span>
                <div>
                  <h4 style={{ fontSize: '1.3em', color: '#667eea', marginBottom: '8px' }}>Accuracy</h4>
                  <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>We continuously monitor and improve our AI models to maintain high accuracy rates.</p>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'start', gap: '15px' }}>
                <span style={{ fontSize: '2em' }}>💬</span>
                <div>
                  <h4 style={{ fontSize: '1.3em', color: '#667eea', marginBottom: '8px' }}>Support</h4>
                  <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>24/7 customer support to help you with any questions or technical issues.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Risk Disclaimer */}
          <section style={{ background: '#fff3cd', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #ffc107' }}>
            <h3 style={{ fontSize: '1.5em', color: '#856404', marginBottom: '15px' }}>⚠️ Important Risk Disclaimer</h3>
            <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#856404' }}>
              TradeFlow is an educational platform. Trading carries significant risk and may not be suitable for all investors. Our signals are for informational purposes only and should not be considered financial advice. Past performance does not guarantee future results. Always conduct your own research and consult with a licensed financial advisor before making investment decisions.
            </p>
          </section>

          {/* CTA */}
          <div style={{ textAlign: 'center', marginTop: '50px' }}>
            <a
              href="/"
              style={{
                display: 'inline-block',
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                color: 'white',
                padding: '18px 40px',
                borderRadius: '50px',
                fontSize: '1.2em',
                fontWeight: 'bold',
                textDecoration: 'none',
                boxShadow: '0 8px 20px rgba(102, 126, 234, 0.4)',
                transition: 'all 0.3s'
              }}
            >
              🚀 Start Trading Now
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}