export default function SignalsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '40px 20px' }}>
        <div style={{ textAlign: 'center', marginBottom: '60px' }}>
          <h1 style={{ fontSize: '3em', color: 'white', marginBottom: '20px', textShadow: '2px 2px 4px rgba(0,0,0,0.2)' }}>
            ⚡ Trading Signals
          </h1>
          <p style={{ fontSize: '1.3em', color: 'rgba(255,255,255,0.9)' }}>
            AI-powered trading signals for global markets
          </p>
        </div>

        <div style={{ background: 'white', borderRadius: '20px', padding: '50px', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              📊 What Are Trading Signals?
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Trading signals are actionable recommendations generated by our AI system that identify high-probability trading opportunities across global financial markets. Each signal provides:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px', marginBottom: '20px' }}>
              <li><strong>Entry Point:</strong> The optimal price level to enter the trade</li>
              <li><strong>Target Price:</strong> The projected profit-taking level</li>
              <li><strong>Stop Loss:</strong> Risk management level to limit potential losses</li>
              <li><strong>Confidence Score:</strong> AI-generated probability of success (85-95%)</li>
              <li><strong>Market Analysis:</strong> Detailed rationale behind the signal</li>
            </ul>
          </section>

          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              🌍 Markets We Cover
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '25px', marginTop: '30px' }}>
              <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '15px', borderTop: '4px solid #0052cc' }}>
                <h3 style={{ fontSize: '1.4em', color: '#0052cc', marginBottom: '15px' }}>📈 US Stocks</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Apple (AAPL), Microsoft (MSFT), Tesla (TSLA), NVIDIA (NVDA), Amazon (AMZN), Google (GOOGL), Meta (META)
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '15px', borderTop: '4px solid #00c853' }}>
                <h3 style={{ fontSize: '1.4em', color: '#00c853', marginBottom: '15px' }}>💶 Forex Pairs</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  EUR/USD, GBP/USD, USD/JPY, AUD/USD, USD/CAD, EUR/GBP, NZD/USD
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '15px', borderTop: '4px solid #ffc107' }}>
                <h3 style={{ fontSize: '1.4em', color: '#ffc107', marginBottom: '15px' }}>🪙 Commodities</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Gold (XAU/USD), Silver (XAG/USD), Crude Oil (WTI), Natural Gas, Copper, Platinum
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '15px', borderTop: '4px solid #ff9800' }}>
                <h3 style={{ fontSize: '1.4em', color: '#ff9800', marginBottom: '15px' }}>₿ Cryptocurrencies</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  Bitcoin (BTC/USD), Ethereum (ETH/USD), Ripple (XRP), Cardano (ADA), Solana (SOL)
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '15px', borderTop: '4px solid #9c27b0' }}>
                <h3 style={{ fontSize: '1.4em', color: '#9c27b0', marginBottom: '15px' }}>🇪🇺 European Stocks</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  LVMH, Shell, HSBC, Volkswagen, Siemens, TotalEnergies, Nestlé
                </p>
              </div>

              <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '15px', borderTop: '4px solid #f44336' }}>
                <h3 style={{ fontSize: '1.4em', color: '#f44336', marginBottom: '15px' }}>📊 Indices</h3>
                <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#555' }}>
                  S&P 500, NASDAQ 100, Dow Jones, FTSE 100, DAX 40, CAC 40, Nikkei 225
                </p>
              </div>
            </div>
          </section>

          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              🤖 How Our AI Generates Signals
            </h2>
            <div style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: '40px', borderRadius: '15px', color: 'white', marginTop: '30px' }}>
              <ol style={{ fontSize: '1.15em', lineHeight: '2', marginLeft: '20px' }}>
                <li><strong>Data Collection:</strong> Our AI monitors real-time price data, volume, news sentiment, and technical indicators from global markets 24/7</li>
                <li><strong>Pattern Recognition:</strong> Advanced machine learning algorithms identify profitable chart patterns, support/resistance levels, and trend reversals</li>
                <li><strong>Fundamental Analysis:</strong> The system analyzes earnings reports, economic data, central bank policies, and geopolitical events</li>
                <li><strong>Risk Assessment:</strong> Each signal is evaluated for risk-reward ratio, ensuring favorable trading conditions</li>
                <li><strong>Signal Generation:</strong> High-probability opportunities are converted into actionable signals with precise entry, target, and stop-loss levels</li>
                <li><strong>Confidence Scoring:</strong> Signals are ranked by confidence level (85-95%) based on historical accuracy and current market conditions</li>
              </ol>
            </div>
          </section>

          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              📈 Signal Performance Statistics
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '25px', marginTop: '30px' }}>
              <div style={{ textAlign: 'center', background: '#f0f7ff', padding: '30px', borderRadius: '15px' }}>
                <div style={{ fontSize: '3em', color: '#0052cc', marginBottom: '10px' }}>78%</div>
                <div style={{ fontSize: '1.1em', color: '#333' }}>Average Win Rate</div>
              </div>
              <div style={{ textAlign: 'center', background: '#e8f5e9', padding: '30px', borderRadius: '15px' }}>
                <div style={{ fontSize: '3em', color: '#00c853', marginBottom: '10px' }}>2.4:1</div>
                <div style={{ fontSize: '1.1em', color: '#333' }}>Risk/Reward Ratio</div>
              </div>
              <div style={{ textAlign: 'center', background: '#fff3e0', padding: '30px', borderRadius: '15px' }}>
                <div style={{ fontSize: '3em', color: '#ff9800', marginBottom: '10px' }}>5-10</div>
                <div style={{ fontSize: '1.1em', color: '#333' }}>Signals Per Day</div>
              </div>
              <div style={{ textAlign: 'center', background: '#fce4ec', padding: '30px', borderRadius: '15px' }}>
                <div style={{ fontSize: '3em', color: '#e91e63', marginBottom: '10px' }}>24/7</div>
                <div style={{ fontSize: '1.1em', color: '#333' }}>Market Monitoring</div>
              </div>
            </div>
          </section>

          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              ⚡ How to Use Our Signals
            </h2>
            <div style={{ background: '#f8f9fa', padding: '30px', borderRadius: '15px', marginTop: '20px' }}>
              <h3 style={{ fontSize: '1.4em', color: '#667eea', marginBottom: '15px' }}>Step-by-Step Guide:</h3>
              <ol style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '20px' }}>
                <li><strong>Sign Up:</strong> Create a free account to access live trading signals</li>
                <li><strong>Choose Your Broker:</strong> Open an account with our verified partner broker Exness (get $50 welcome bonus)</li>
                <li><strong>Monitor Signals:</strong> Check the signals dashboard daily for new high-probability opportunities</li>
                <li><strong>Analyze the Signal:</strong> Review entry price, target, stop-loss, and confidence score</li>
                <li><strong>Execute the Trade:</strong> Place the trade on your broker's platform following the signal parameters</li>
                <li><strong>Set Risk Management:</strong> Always use the recommended stop-loss to protect your capital</li>
                <li><strong>Take Profits:</strong> Close the position when the target price is reached or adjust based on market conditions</li>
                <li><strong>Track Performance:</strong> Monitor your trading statistics in the dashboard</li>
              </ol>
            </div>
          </section>

          <section style={{ background: '#fff3cd', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #ffc107', marginBottom: '50px' }}>
            <h3 style={{ fontSize: '1.5em', color: '#856404', marginBottom: '15px' }}>⚠️ Risk Management Best Practices</h3>
            <ul style={{ fontSize: '1.05em', lineHeight: '1.8', color: '#856404', marginLeft: '20px' }}>
              <li><strong>Never risk more than 1-2% of your trading capital per trade</strong></li>
              <li><strong>Always use stop-loss orders</strong> to limit potential losses</li>
              <li><strong>Diversify across multiple signals</strong> - don't put all capital in one trade</li>
              <li><strong>Start with demo accounts</strong> to practice before trading with real money</li>
              <li><strong>Don't trade with money you can't afford to lose</strong></li>
              <li><strong>Review past signal performance</strong> to understand accuracy rates</li>
              <li><strong>Understand that no signal is 100% guaranteed</strong> - losses are part of trading</li>
            </ul>
          </section>

          <div style={{ textAlign: 'center', marginTop: '50px' }}>
            <a
              href="/"
              style={{
                display: 'inline-block',
                background: 'linear-gradient(135deg, #00c853 0%, #00a344 100%)',
                color: 'white',
                padding: '18px 40px',
                borderRadius: '50px',
                fontSize: '1.2em',
                fontWeight: 'bold',
                textDecoration: 'none',
                boxShadow: '0 8px 20px rgba(0, 200, 83, 0.4)',
                transition: 'all 0.3s',
                marginRight: '20px'
              }}
            >
              ⚡ View Live Signals
            </a>
            <a
              href="https://one.exnessonelink.com/boarding/sign-up/a/scknhe9tsg"
              target="_blank"
              rel="noopener noreferrer"
              style={{
                display: 'inline-block',
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                color: 'white',
                padding: '18px 40px',
                borderRadius: '50px',
                fontSize: '1.2em',
                fontWeight: 'bold',
                textDecoration: 'none',
                boxShadow: '0 8px 20px rgba(102, 126, 234, 0.4)',
                transition: 'all 0.3s'
              }}
            >
              🚀 Start Trading with Exness
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}