export default function RiskPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '40px 20px' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '60px' }}>
          <h1 style={{ fontSize: '3em', color: 'white', marginBottom: '20px', textShadow: '2px 2px 4px rgba(0,0,0,0.2)' }}>
            Risk Disclosure
          </h1>
          <p style={{ fontSize: '1.3em', color: 'rgba(255,255,255,0.9)', maxWidth: '800px', margin: '0 auto' }}>
            Important information about trading risks and our educational services.
          </p>
          <p style={{ fontSize: '1.1em', color: 'rgba(255,255,255,0.8)', marginTop: '15px' }}>
            Last Updated: October 23, 2025
          </p>
        </div>

        {/* Main Content */}
        <div style={{ background: 'white', borderRadius: '20px', padding: '50px', boxShadow: '0 20px 60px rgba(0,0,0,0.3)' }}>

          {/* Critical Warning */}
          <section style={{ background: '#ffebee', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #f44336', marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2em', color: '#c62828', marginBottom: '15px' }}>CRITICAL RISK WARNING</h2>
            <p style={{ fontSize: '1.2em', lineHeight: '1.8', color: '#c62828', fontWeight: 'bold', marginBottom: '15px' }}>
              TRADING IN FINANCIAL INSTRUMENTS CARRIES A HIGH LEVEL OF RISK AND MAY NOT BE SUITABLE FOR ALL INVESTORS. YOU CAN LOSE MORE THAN YOUR INITIAL INVESTMENT.
            </p>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#c62828' }}>
              Before trading, you should carefully consider your investment objectives, level of experience, and risk appetite. You should not invest money that you cannot afford to lose. TradeFlow is an educational platform and does not provide financial advice.
            </p>
          </section>

          {/* Introduction */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              1. Introduction
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              This Risk Disclosure document is designed to inform you of the risks associated with trading in financial markets and using trading signals provided by TradeFlow.
            </p>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333' }}>
              By using TradeFlow's services, you acknowledge that you have read, understood, and accepted the risks described in this document.
            </p>
          </section>

          {/* Nature of Services */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              2. Nature of Our Services
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px', fontWeight: 'bold' }}>
              TradeFlow is an educational platform. We provide:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Trading signals generated by AI algorithms for educational purposes</li>
              <li>Market analysis and commentary</li>
              <li>Educational content about trading strategies and techniques</li>
              <li>News aggregation and market sentiment analysis</li>
            </ul>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginTop: '15px', fontWeight: 'bold' }}>
              WE DO NOT:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Provide personalized investment advice or recommendations</li>
              <li>Manage client funds or portfolios</li>
              <li>Act as a broker, dealer, or financial institution</li>
              <li>Guarantee any trading results or profits</li>
              <li>Make investment decisions on your behalf</li>
            </ul>
          </section>

          {/* General Trading Risks */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              3. General Trading Risks
            </h2>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              3.1 Risk of Loss
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Trading in financial markets involves substantial risk of loss. You may lose your entire investment or more than your initial deposit, especially when trading with leverage. Past performance is not indicative of future results.
            </p>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              3.2 Market Volatility
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Financial markets can be extremely volatile. Prices can move rapidly in unfavorable directions, resulting in significant losses in short periods. Market conditions can change without warning.
            </p>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              3.3 Leverage Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Trading with leverage (margin) amplifies both potential profits and losses. A small market movement can lead to proportionally larger movements in your account balance. You may lose more than your initial investment.
            </p>
            <div style={{ background: '#fff3cd', padding: '20px', borderRadius: '10px', marginTop: '15px' }}>
              <p style={{ fontSize: '1.05em', lineHeight: '1.6', color: '#856404', fontWeight: 'bold' }}>
                Example: With 100:1 leverage, a 1% adverse price movement could result in a 100% loss of your invested capital.
              </p>
            </div>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              3.4 Liquidity Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Some markets or instruments may have low liquidity, making it difficult to enter or exit positions at desired prices. This can result in slippage and larger losses than anticipated.
            </p>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              3.5 Gap Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333' }}>
              Markets can "gap" - open at significantly different prices from the previous close. This can occur over weekends, during news releases, or due to unexpected events. Stop-loss orders may not protect you from gap movements.
            </p>
          </section>

          {/* Specific Market Risks */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              4. Specific Market Risks
            </h2>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              4.1 Forex (Foreign Exchange) Trading
            </h3>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Exchange rates fluctuate continuously and can be highly volatile</li>
              <li>Political and economic events can cause rapid price movements</li>
              <li>Interest rate differentials affect currency values</li>
              <li>Weekend and overnight gaps can occur</li>
              <li>High leverage is common (up to 500:1), magnifying both gains and losses</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              4.2 Cryptocurrency Trading
            </h3>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Extremely high volatility - prices can swing 20%+ in a single day</li>
              <li>Market operates 24/7 with no circuit breakers</li>
              <li>Regulatory uncertainty and potential government actions</li>
              <li>Security risks including hacking and exchange failures</li>
              <li>Lack of investor protections compared to traditional markets</li>
              <li>Potential for total loss of investment</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              4.3 Stock Trading
            </h3>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Company-specific risks (earnings, management, competition)</li>
              <li>Market risk affecting entire sectors or markets</li>
              <li>Economic indicators can cause significant volatility</li>
              <li>Overnight gaps due to after-hours news</li>
              <li>Dividend cuts or eliminations can affect prices</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              4.4 Commodities Trading
            </h3>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Weather, geopolitical events, and supply disruptions affect prices</li>
              <li>High leverage commonly available</li>
              <li>Seasonal patterns and inventory levels influence prices</li>
              <li>Currency fluctuations affect commodity values</li>
              <li>Storage and delivery considerations for physical commodities</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              4.5 Indices Trading
            </h3>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Broad market exposure to multiple stocks</li>
              <li>Economic data releases cause significant volatility</li>
              <li>Correlation between global markets can amplify movements</li>
              <li>Gap risk during market closures</li>
            </ul>
          </section>

          {/* AI and Technology Risks */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              5. AI Trading Signals and Technology Risks
            </h2>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              5.1 No Guarantee of Accuracy
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Our AI-generated trading signals are based on historical data analysis and algorithms. They do not guarantee future results. Markets are unpredictable, and AI models can be wrong.
            </p>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              5.2 Algorithm Limitations
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              AI algorithms have limitations:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Cannot predict unprecedented events (black swan events)</li>
              <li>May not adapt quickly to changing market conditions</li>
              <li>Can be affected by data quality and availability issues</li>
              <li>May generate false signals or miss trading opportunities</li>
              <li>Past patterns may not repeat in the future</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              5.3 Technical Failures
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Technology can fail due to:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Internet connectivity issues</li>
              <li>Server downtime or maintenance</li>
              <li>Software bugs or glitches</li>
              <li>Data feed interruptions</li>
              <li>Cybersecurity incidents</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              5.4 Delayed or Missed Signals
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333' }}>
              Trading signals may be delayed due to technical issues, and timing is critical in trading. By the time you receive and act on a signal, market conditions may have changed significantly.
            </p>
          </section>

          {/* Performance Disclaimers */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              6. Performance Disclaimers
            </h2>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              6.1 Past Performance
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px', fontWeight: 'bold' }}>
              PAST PERFORMANCE IS NOT INDICATIVE OF FUTURE RESULTS. Historical win rates, profit percentages, and returns shown on our website or in marketing materials do not guarantee similar future performance.
            </p>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              6.2 Hypothetical or Simulated Results
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Some performance results may be based on hypothetical or simulated trading. These results have inherent limitations:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>No actual money is at risk in simulations</li>
              <li>Simulations cannot account for all real-world trading conditions</li>
              <li>Results may be over-optimized for historical data</li>
              <li>Transaction costs and slippage may not be fully represented</li>
              <li>Emotional factors affecting real trading are not present</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              6.3 No Guarantee of Profit
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', fontWeight: 'bold' }}>
              We make no guarantees or warranties regarding profitability. Many traders lose money, and you should not expect to profit from using our signals or services.
            </p>
          </section>

          {/* Additional Risks */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              7. Additional Risks
            </h2>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              7.1 Broker Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              When you trade through a broker (including partners like Exness), you face:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Risk of broker insolvency or bankruptcy</li>
              <li>Potential for unethical broker practices</li>
              <li>Platform technical issues or outages</li>
              <li>Regulatory changes affecting broker operations</li>
              <li>Limited investor protection in some jurisdictions</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              7.2 Regulatory Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Government regulations can change:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Leverage restrictions may be imposed</li>
              <li>Trading of certain instruments may be banned</li>
              <li>Tax treatment of trading profits may change</li>
              <li>Reporting requirements may increase</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              7.3 Psychological Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Trading can be emotionally challenging:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Stress and anxiety from potential losses</li>
              <li>Overtrading due to fear of missing out (FOMO)</li>
              <li>Revenge trading after losses</li>
              <li>Overconfidence after winning streaks</li>
              <li>Emotional decision-making instead of rational analysis</li>
            </ul>

            <h3 style={{ fontSize: '1.6em', color: '#764ba2', marginBottom: '15px', marginTop: '30px' }}>
              7.4 Time Zone and Execution Risk
            </h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333' }}>
              Our signals are time-sensitive. If you are in a different time zone or unable to trade immediately when signals are issued, market conditions may have changed, reducing effectiveness or increasing risk.
            </p>
          </section>

          {/* Not Financial Advice */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              8. Not Financial Advice
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px', fontWeight: 'bold' }}>
              TRADEFLOW PROVIDES EDUCATIONAL CONTENT AND TRADING SIGNALS FOR INFORMATIONAL PURPOSES ONLY. OUR SERVICES DO NOT CONSTITUTE FINANCIAL, INVESTMENT, TAX, OR LEGAL ADVICE.
            </p>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              You should:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Conduct your own research and due diligence</li>
              <li>Consult with a licensed financial advisor before making investment decisions</li>
              <li>Consider your financial situation, investment objectives, and risk tolerance</li>
              <li>Only trade with money you can afford to lose</li>
              <li>Never borrow money to trade</li>
            </ul>
          </section>

          {/* Suitability */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              9. Suitability
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              Trading may not be suitable for you if:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>You cannot afford to lose your invested capital</li>
              <li>You have limited trading experience or knowledge</li>
              <li>You have low risk tolerance</li>
              <li>You need guaranteed income or returns</li>
              <li>You are trading with borrowed money or funds needed for living expenses</li>
              <li>You have a history of compulsive behavior or gambling addiction</li>
            </ul>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginTop: '15px', fontWeight: 'bold' }}>
              It is your responsibility to determine whether trading is appropriate for you based on your individual circumstances.
            </p>
          </section>

          {/* User Responsibilities */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              10. Your Responsibilities
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              As a user of TradeFlow, you are responsible for:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Making your own trading decisions</li>
              <li>Understanding the risks before trading</li>
              <li>Managing your risk exposure and position sizes</li>
              <li>Setting appropriate stop-loss orders</li>
              <li>Monitoring your trades and account balance</li>
              <li>Complying with applicable laws and regulations</li>
              <li>Paying taxes on trading profits</li>
              <li>Verifying signal information before acting</li>
              <li>Maintaining adequate capital and margin</li>
            </ul>
          </section>

          {/* Limitation of Liability */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              11. Limitation of Liability
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px', fontWeight: 'bold' }}>
              TRADEFLOW, ITS OWNERS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY TRADING LOSSES, DAMAGES, OR EXPENSES INCURRED AS A RESULT OF USING OUR SERVICES, SIGNALS, OR CONTENT.
            </p>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333' }}>
              This includes but is not limited to losses from:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>Following or not following our trading signals</li>
              <li>Technical failures or signal delays</li>
              <li>Inaccurate or incomplete information</li>
              <li>Broker failures or issues</li>
              <li>Market volatility or adverse price movements</li>
              <li>Your trading decisions and actions</li>
            </ul>
          </section>

          {/* Acknowledgment */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              12. Acknowledgment
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              By using TradeFlow, you acknowledge that:
            </p>
            <ul style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginLeft: '30px' }}>
              <li>You have read and understood this Risk Disclosure</li>
              <li>You accept all risks associated with trading</li>
              <li>You understand that you may lose your entire investment</li>
              <li>You are solely responsible for your trading decisions</li>
              <li>TradeFlow is not a financial advisor and does not provide investment advice</li>
              <li>Past performance does not guarantee future results</li>
              <li>No guarantee of profit or success is made</li>
            </ul>
          </section>

          {/* Contact Information */}
          <section style={{ marginBottom: '50px' }}>
            <h2 style={{ fontSize: '2.2em', color: '#667eea', marginBottom: '20px', borderBottom: '3px solid #667eea', paddingBottom: '10px' }}>
              13. Questions
            </h2>
            <p style={{ fontSize: '1.15em', lineHeight: '1.8', color: '#333', marginBottom: '15px' }}>
              If you have questions about this Risk Disclosure or trading risks, please contact us:
            </p>
            <div style={{ background: '#f8f9fa', padding: '25px', borderRadius: '10px', marginTop: '20px' }}>
              <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '10px' }}>
                <strong>Email:</strong> risk@tradeflow.com
              </p>
              <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333', marginBottom: '10px' }}>
                <strong>Support:</strong> support@tradeflow.com
              </p>
              <p style={{ fontSize: '1.1em', lineHeight: '1.8', color: '#333' }}>
                <strong>Note:</strong> We can answer questions about our services but cannot provide personalized investment advice.
              </p>
            </div>
          </section>

          {/* Final Warning */}
          <section style={{ background: '#ffebee', padding: '30px', borderRadius: '15px', borderLeft: '5px solid #f44336' }}>
            <h3 style={{ fontSize: '1.5em', color: '#c62828', marginBottom: '15px' }}>Final Important Warning</h3>
            <p style={{ fontSize: '1.1em', lineHeight: '1.6', color: '#c62828', marginBottom: '15px' }}>
              If you do not understand the risks described in this document, or if you are not comfortable with these risks, DO NOT USE OUR SERVICES OR ENGAGE IN TRADING.
            </p>
            <p style={{ fontSize: '1.1em', lineHeight: '1.6', color: '#c62828', fontWeight: 'bold' }}>
              Only risk capital that you can afford to lose. Consult with a licensed financial professional before making any investment decisions.
            </p>
          </section>

          {/* Back to Home */}
          <div style={{ textAlign: 'center', marginTop: '50px' }}>
            <a
              href="/"
              style={{
                display: 'inline-block',
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                color: 'white',
                padding: '18px 40px',
                borderRadius: '50px',
                fontSize: '1.2em',
                fontWeight: 'bold',
                textDecoration: 'none',
                boxShadow: '0 8px 20px rgba(102, 126, 234, 0.4)',
                transition: 'all 0.3s'
              }}
            >
              Back to Home
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
